#!/usr/bin/env bash
set -euo pipefail

# One-shot release: bump the package version, build all platforms, publish a
# NEW versioned GitHub release, and regenerate release.properties (the single
# source of truth that the podspecs and android/build.gradle.kts read for the
# tag + SHA-256s). No manual SHA pasting; no clobbering an existing tag.
#
# Prerequisites (macOS): Xcode + CLI tools, gh authenticated, ANDROID_NDK_HOME.
# Usage: native/scripts/release.sh [major|minor|patch]   (default: patch)

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PKG_DIR="$(cd "${SCRIPT_DIR}/../.." && pwd)"
REL_DIR="${PKG_DIR}/native/build/release"
PUBSPEC="${PKG_DIR}/pubspec.yaml"
LOCK_FILE="${PKG_DIR}/release.properties"
REPO="ketanchoyal/auddio_whisper_engine"
BUMP="${1:-patch}"

source "${SCRIPT_DIR}/setup_prereqs.sh" || {
  echo "ERROR: prerequisite setup failed." >&2
  exit 1
}

current="$(grep -E '^version:' "${PUBSPEC}" | head -1 | sed -E 's/^version:[[:space:]]*//' | tr -d '[:space:]')"
IFS='.' read -r major minor patch <<< "${current}"
case "${BUMP}" in
  major) major=$((major + 1)); minor=0; patch=0 ;;
  minor) minor=$((minor + 1)); patch=0 ;;
  patch) patch=$((patch + 1)) ;;
  *) echo "ERROR: bump must be major|minor|patch (got '${BUMP}')" >&2; exit 1 ;;
esac
new_version="${major}.${minor}.${patch}"
tag="whisper-v${new_version}"

if gh release view "${tag}" --repo "${REPO}" >/dev/null 2>&1; then
  echo "ERROR: release ${tag} already exists. Bump again or delete it first." >&2
  exit 1
fi

echo ">> Releasing ${tag} (was ${current})"

echo ">> Building iOS..."
"${SCRIPT_DIR}/build_ios.sh"
echo ">> Building macOS..."
"${SCRIPT_DIR}/build_macos.sh"
echo ">> Building Android..."
"${SCRIPT_DIR}/build_android.sh"

echo ">> Staging artifacts..."
"${SCRIPT_DIR}/checksums.sh" >/dev/null

sha() {
  if command -v shasum >/dev/null 2>&1; then
    shasum -a 256 "$1" | awk '{print $1}'
  else
    sha256sum "$1" | awk '{print $1}'
  fi
}

# Parallel indexed arrays: macOS ships bash 3.2, which has no associative
# arrays. KEYS[i] names the release.properties suffix; FILES[i] the artifact.
KEYS=(IOS MACOS ANDROID_ARM64_V8A ANDROID_ARMEABI_V7A ANDROID_X86_64)
FILES=(
  "libauddio_whisper_ios.xcframework.zip"
  "libauddio_whisper_macos.xcframework.zip"
  "libauddio_whisper-arm64-v8a.so"
  "libauddio_whisper-armeabi-v7a.so"
  "libauddio_whisper-x86_64.so"
)

ASSETS=()
SHAS=()
idx=0
while [ "${idx}" -lt "${#KEYS[@]}" ]; do
  file="${REL_DIR}/${FILES[$idx]}"
  if [ ! -e "${file}" ]; then
    echo "ERROR: expected artifact missing: ${file}" >&2
    exit 1
  fi
  SHAS[$idx]="$(sha "${file}")"
  ASSETS+=("${file}")
  idx=$((idx + 1))
done

echo ">> Creating GitHub release ${tag}..."
gh release create "${tag}" \
  --repo "${REPO}" \
  --title "${tag}" \
  --notes "Prebuilt whisper.cpp engine binaries (${new_version})." \
  "${ASSETS[@]}"

# Bump the package version only AFTER a successful publish, so a failed
# release never leaves a phantom version ahead of what's on GitHub.
sed -i.bak -E "s/^version:.*/version: ${new_version}/" "${PUBSPEC}" && rm -f "${PUBSPEC}.bak"

# Update Package.swift files with the new tag and checksums
IOS_PKG="${PKG_DIR}/ios/auddio_whisper_engine/Package.swift"
MACOS_PKG="${PKG_DIR}/macos/auddio_whisper_engine/Package.swift"

if [ -f "${IOS_PKG}" ]; then
  echo ">> Updating ${IOS_PKG}..."
  sed -i.bak -E \
    -e "s|releases/download/[^/]+/libauddio_whisper_ios\.xcframework\.zip|releases/download/${tag}/libauddio_whisper_ios.xcframework.zip|g" \
    -e "s|checksum: \"[0-9a-f]+\"|checksum: \"${SHAS[0]}\"|g" \
    "${IOS_PKG}" && rm -f "${IOS_PKG}.bak"
fi

if [ -f "${MACOS_PKG}" ]; then
  echo ">> Updating ${MACOS_PKG}..."
  sed -i.bak -E \
    -e "s|releases/download/[^/]+/libauddio_whisper_macos\.xcframework\.zip|releases/download/${tag}/libauddio_whisper_macos.xcframework.zip|g" \
    -e "s|checksum: \"[0-9a-f]+\"|checksum: \"${SHAS[1]}\"|g" \
    "${MACOS_PKG}" && rm -f "${MACOS_PKG}.bak"
fi

{
  echo "# Generated by native/scripts/release.sh - do not edit by hand."
  echo "# Single source of truth for the prebuilt-binary release, read by the"
  echo "# ios/macos podspecs and android/build.gradle.kts."
  echo "RELEASE_TAG=${tag}"
  echo "RELEASE_REPO=${REPO}"
  idx=0
  while [ "${idx}" -lt "${#KEYS[@]}" ]; do
    echo "SHA_${KEYS[$idx]}=${SHAS[$idx]}"
    idx=$((idx + 1))
  done
} > "${LOCK_FILE}"

echo ""
echo ">> Released ${tag}. Wrote ${LOCK_FILE}:"
cat "${LOCK_FILE}"
echo ""
echo ">> Commit changed files (pubspec.yaml, release.properties, and Package.swift manifests)."
