import java.security.MessageDigest

plugins {
    id("com.android.library")
}

// Release tag, repo, version, and per-ABI SHA-256s come from release.properties
// (generated by native/scripts/release.sh), so a new release needs no edits here.
val releaseProps = java.util.Properties().apply {
    file("../release.properties").inputStream().use { load(it) }
}
fun releaseProp(key: String): String =
    releaseProps.getProperty(key) ?: error("release.properties missing '$key'")

val RELEASE_TAG = releaseProp("RELEASE_TAG")
val RELEASE_REPO = releaseProp("RELEASE_REPO")

group = "app.audiio.auddio_whisper_engine"
version = RELEASE_TAG.removePrefix("whisper-v")

android {
    namespace = "app.audiio.auddio_whisper_engine"
    compileSdk = 36

    defaultConfig {
        minSdk = 24
        ndk {
            abiFilters += listOf("arm64-v8a", "armeabi-v7a", "x86_64")
        }
    }
}

val downloadWhisperLibraries = tasks.register("downloadWhisperLibraries") {
    val abis = mapOf(
        "arm64-v8a" to mapOf(
            "asset" to "libauddio_whisper-arm64-v8a.so",
            "sha256" to releaseProp("SHA_ANDROID_ARM64_V8A")
        ),
        "armeabi-v7a" to mapOf(
            "asset" to "libauddio_whisper-armeabi-v7a.so",
            "sha256" to releaseProp("SHA_ANDROID_ARMEABI_V7A")
        ),
        "x86_64" to mapOf(
            "asset" to "libauddio_whisper-x86_64.so",
            "sha256" to releaseProp("SHA_ANDROID_X86_64")
        )
    )

    doLast {
        val jniLibsDir = file("src/main/jniLibs")
        val abiFilters = android.defaultConfig.ndk.abiFilters.ifEmpty { abis.keys }
        abis.filter { it.key in abiFilters }.forEach { (abi, info) ->
            val expectedHash = info["sha256"]!!
            val abiDir = file("$jniLibsDir/$abi")
            if (!abiDir.exists()) abiDir.mkdirs()
            val targetFile = file("$abiDir/libauddio_whisper.so")

            if (targetFile.exists() && sha256(targetFile) == expectedHash) return@forEach
            if (targetFile.exists()) targetFile.delete()

            val asset = info["asset"]!!
            println("Downloading $asset for $abi via gh release download")
            val proc = ProcessBuilder(
                "gh", "release", "download", RELEASE_TAG,
                "--repo", RELEASE_REPO,
                "--pattern", asset,
                "--output", targetFile.absolutePath,
                "--clobber"
            ).redirectErrorStream(true).start()
            val output = proc.inputStream.bufferedReader().readText()
            if (proc.waitFor() != 0) {
                throw GradleException(
                    "gh release download failed for $abi ($asset). " +
                        "Ensure gh is installed and authenticated.\n$output"
                )
            }
            if (sha256(targetFile) != expectedHash) {
                targetFile.delete()
                throw GradleException("SHA-256 verification failed for $abi")
            }
        }
    }
}

fun sha256(f: java.io.File): String =
    MessageDigest.getInstance("SHA-256").digest(f.readBytes())
        .joinToString("") { "%02x".format(it) }

tasks.configureEach {
    if (name.contains("preBuild")) {
        dependsOn(downloadWhisperLibraries)
    }
}
