#
# auddio_whisper_engine iOS podspec
#
# The native whisper.cpp engine ships as a prebuilt libauddio_whisper.xcframework
# (device arm64 + simulator arm64/x86_64) downloaded from GitHub Releases and
# SHA-256 verified, mirroring the mpv_audio_kit delivery model. The Dart side
# loads it via DynamicLibrary.open. Build it with native/scripts/build_ios.sh.
#
# Release tag + SHA-256 come from release.properties (generated by
# native/scripts/release.sh), so a new release needs no podspec edits.
_props = {}
File.foreach(File.join(__dir__, '..', 'release.properties')) do |line|
  text = line.strip
  next if text.empty? || text.start_with?('#')
  key, value = text.split('=', 2)
  _props[key] = value
end
_tag = _props.fetch('RELEASE_TAG')
_repo = _props.fetch('RELEASE_REPO')
_sha = _props.fetch('SHA_IOS')
_version = _tag.sub(/^whisper-v/, '')

Pod::Spec.new do |s|
  s.name             = 'auddio_whisper_engine'
  s.version          = _version
  s.summary          = 'Prebuilt whisper.cpp engine (Metal + CoreML) for Auddio.'
  s.description      = 'On-device chapter transcription with per-word DTW timestamps.'
  s.homepage         = 'https://github.com/ketanchoyal/auddio_whisper_engine'
  s.license          = { :type => 'Proprietary' }
  s.author           = { 'Auddio' => 'audiio.app' }
  s.source           = { :path => '.' }
  s.platform         = :ios, '16.4'
  s.dependency 'Flutter'

  # CoreML + Foundation: CoreML encoder path. Metal + Accelerate: ggml GPU/BLAS.
  # AudioToolbox: native in-memory audio decoding (ExtAudioFile).
  s.frameworks = 'CoreML', 'Foundation', 'Metal', 'Accelerate', 'AudioToolbox'

  # ── Prebuilt xcframework ──────────────────────────────────────────────────
  s.prepare_command = <<-CMD
    RELEASE_TAG="#{_tag}"
    REPO="#{_repo}"
    ASSET="libauddio_whisper_ios.xcframework.zip"
    EXPECTED_SHA256="#{_sha}"

    mkdir -p Frameworks
    ZIP_FILE="Frameworks/libauddio_whisper_xcframework.zip"
    MARKER="Frameworks/.installed_sha"
    DOWNLOAD_NEEDED=1

    # Skip re-download only when the installed framework's recorded SHA matches
    # the expected one. The verified zip is deleted after extraction, so a mere
    # "directory exists" check would pin the FIRST download forever and never
    # pick up a new release. The marker makes a changed SHA force a re-download.
    if [ -f "Frameworks/auddio_whisper.xcframework/Info.plist" ] && \
       [ -f "$MARKER" ] && \
       [ "$(cat "$MARKER" 2>/dev/null)" = "$EXPECTED_SHA256" ]; then
      DOWNLOAD_NEEDED=0
    fi

    # awe:remote:begin
    # Try public curl download first, fallback to gh CLI if it fails.
    if [ $DOWNLOAD_NEEDED -eq 1 ]; then
      rm -rf "Frameworks/auddio_whisper.xcframework" "$ZIP_FILE" "$MARKER"
      
      URL="https://github.com/${REPO}/releases/download/${RELEASE_TAG}/${ASSET}"
      echo "Downloading $ASSET from $URL..."
      if curl -L -s -f -o "$ZIP_FILE" "$URL"; then
        echo "Download successful."
      else
        echo "Public download failed. Falling back to gh CLI..."
        if ! command -v gh >/dev/null 2>&1; then
          echo "ERROR: curl failed and gh CLI is not installed." >&2
          exit 1
        fi
        gh release download "$RELEASE_TAG" --repo "$REPO" --pattern "$ASSET" --output "$ZIP_FILE" --clobber || {
          echo "ERROR: gh release download failed for $ASSET" >&2
          exit 1
        }
      fi

      ACTUAL_SHA256=$(shasum -a 256 "$ZIP_FILE" | awk '{ print $1 }')
      if [ "$ACTUAL_SHA256" != "$EXPECTED_SHA256" ]; then
        echo "ERROR: SHA-256 verification failed for $ZIP_FILE"
        rm -f "$ZIP_FILE"
        exit 1
      fi
      unzip -o "$ZIP_FILE" -d Frameworks/
      rm -f "$ZIP_FILE"
      # Legacy renaming fallback: if zip unzips to libauddio_whisper.xcframework, rename it to auddio_whisper.xcframework.
      if [ -d "Frameworks/libauddio_whisper.xcframework" ]; then
        rm -rf "Frameworks/auddio_whisper.xcframework"
        mv "Frameworks/libauddio_whisper.xcframework" "Frameworks/auddio_whisper.xcframework"
      fi
      echo "$EXPECTED_SHA256" > "$MARKER"
    fi
    # awe:remote:end
  CMD

  s.vendored_frameworks = 'Frameworks/auddio_whisper.xcframework'
  s.pod_target_xcconfig = { 'DEFINES_MODULE' => 'YES' }
end
